/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Lab = {
  _id: string;
  _type: "lab";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  orderRank?: string;
  line?: string;
  href?: string;
  kind?: "live" | "concept";
  status?: string;
  shot?: string;
  shotAlt?: string;
  featured?: boolean;
  stack?: string;
  approach?: string;
  meta?: string;
  references?: Array<{
    label?: string;
    href?: string;
    _type: "referenceLink";
    _key: string;
  }>;
  plate?: "map" | "sql";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  orderRank?: string;
  featured?: boolean;
  line?: string;
  url?: string;
  note?: string;
  stack?: string;
  approach?: string;
  shot?: string;
  shotAlt?: string;
  shotMobile?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Lab
  | Slug
  | Project
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank asc) {    "slug": slug.current,    name,    line,    url,    note,    stack,    approach,    shot,    shotAlt,    shotMobile,    featured  }
export type PROJECTS_QUERY_RESULT = Array<{
  slug: string | null;
  name: string | null;
  line: string | null;
  url: string | null;
  note: string | null;
  stack: string | null;
  approach: string | null;
  shot: string | null;
  shotAlt: string | null;
  shotMobile: string | null;
  featured: boolean | null;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: LABS_INDEX_QUERY
// Query: *[_type == "lab"] | order(orderRank asc) {    "slug": slug.current,    name,    line,    href,    kind,    status,    shot,    shotAlt  }
export type LABS_INDEX_QUERY_RESULT = Array<{
  slug: string | null;
  name: string | null;
  line: string | null;
  href: string | null;
  kind: "concept" | "live" | null;
  status: string | null;
  shot: string | null;
  shotAlt: string | null;
}>;

// Source: ../lib/sanity/queries.ts
// Variable: LABS_FEATURED_QUERY
// Query: *[_type == "lab" && featured == true] | order(orderRank asc) {    "slug": slug.current,    name,    line,    stack,    approach,    "url": href,    shot,    shotAlt,    status,    meta,    plate,    references[]{ label, href }  }
export type LABS_FEATURED_QUERY_RESULT = Array<{
  slug: string | null;
  name: string | null;
  line: string | null;
  stack: string | null;
  approach: string | null;
  url: string | null;
  shot: string | null;
  shotAlt: string | null;
  status: string | null;
  meta: string | null;
  plate: "map" | "sql" | null;
  references: Array<{
    label: string | null;
    href: string | null;
  }> | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(orderRank asc) {\n    "slug": slug.current,\n    name,\n    line,\n    url,\n    note,\n    stack,\n    approach,\n    shot,\n    shotAlt,\n    shotMobile,\n    featured\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "lab"] | order(orderRank asc) {\n    "slug": slug.current,\n    name,\n    line,\n    href,\n    kind,\n    status,\n    shot,\n    shotAlt\n  }\n': LABS_INDEX_QUERY_RESULT;
    '\n  *[_type == "lab" && featured == true] | order(orderRank asc) {\n    "slug": slug.current,\n    name,\n    line,\n    stack,\n    approach,\n    "url": href,\n    shot,\n    shotAlt,\n    status,\n    meta,\n    plate,\n    references[]{ label, href }\n  }\n': LABS_FEATURED_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
