import type { MetadataRoute } from "next";

/**
 * robots.txt.
 *
 * The site had none, which is survivable on its own — crawlers assume they may
 * crawl what they can reach. What it cost was discovery of /sql: the SQL
 * reference pages live in a separate Next app served here through a rewrite,
 * so nothing on this site links deeply into them and there was no sitemap
 * naming them either. Both sitemaps are listed here so the zone's pages are
 * found on the first crawl rather than whenever a link happens to appear.
 *
 * `/sql/sitemap.xml` is generated by the zone and reaches here through the
 * same rewrite as its pages; it lists absolute vertexapps.dev URLs, not the
 * zone's own deployment host.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: "*", allow: "/" },
    sitemap: [
      "https://vertexapps.dev/sitemap.xml",
      "https://vertexapps.dev/sql/sitemap.xml",
    ],
    host: "https://vertexapps.dev",
  };
}